### PR TITLE
Upated references for v1_LE_ssp370 and all v2_LE metadata files

### PR DESCRIPTION
**Pull request by TonyB9000**
Added the reference materials for v1_LE_ssp370 and all v2_LE metadata files.

@chengzhuzhang Ready to merge to master on your review.

### CODE REVIEW

**Review by chengzhuzhang — COMMENTED** [review]
Hi Tony, 

For the ssp370 20ensembles, I think the plan is to add the additional two FAsullo papers, so we want to keep the Stevenson paper. 

For v2, we also want to keep the Golaz paper. In addition, the first  5 v2 historical ensembles are a already published, and we don't need to update them? I don't know if there is a limit in text length. If so, we can limit to show only first a few authors for the Fasullo et al. papers.

**Comment by TonyB9000** [comment]
OK - the first 5 v2 historical ensembles should be untouched (only ens 6-21 affected.)  If they need updates, I will need to retract/republish.

I mistakenly thought that the existing references were left-over from the copy of previous metadata files, and should not apply.

From what I gather, the 3-hour, 6315 datasets, 40,000+ file updates are also bogus, since their references were replaced.

I will attempt to produce the entire reference section for each "wave" and have you approve/edit before issuing new updates.  At least, I've essentially automated the process to it won't be hard to employ, once I get it right.

SO, I take it that "ssp370" (v1 and v2) get the Stevenson and two Fasullo paper references,
The v2 historical (16 ensembles, 6-21) get the Golas references - but what else?

The v1 historical (20 ensembles) were published LONG ago, I'll retrieve their references and produce a report.

Expect an email - I'm not sure how to embed an excel table into this git message - although I can try.

**Comment by chengzhuzhang** [comment]
> From what I gather, the 3-hour, 6315 datasets, 40,000+ file updates are also bogus, since their references were replaced.
> 
Yes, let's first finalize the metadate definition files here then tough the files.

> I will attempt to produce the entire reference section for each "wave" and have you approve/edit before issuing new updates. At least, I've essentially automated the process to it won't be hard to employ, once I get it right.
> 
Good news taht the process is automated!

> SO, I take it that "ssp370" (v1 and v2) get the Stevenson and two Fasullo paper references, The v2 historical (16 ensembles, 6-21) get the Golas references - but what else?
> 
The v2 historical (16 ensembles, 6-21) get the Golas references  and wo Fasullo paper references,

> The v1 historical (20 ensembles) were published LONG ago, I'll retrieve their references and produce a report.
> 
No need! They are good as is. 

> Expect an email - I'm not sure how to embed an excel table into this git message - although I can try.

**Comment by TonyB9000** [comment]
@chengzhuzhang Corrected the repo metadata for the LE materials.  Let me know how it looks!

**Review by chengzhuzhang — COMMENTED** [review]
the v2 historical_r1-r5 are already published. So the metadata files don't need to be changed. Other than that, all looks good!

**Comment by chengzhuzhang** [comment]
@TonyB9000 could you address the review and finalize this PR for merging?

**Comment by TonyB9000** [comment]
I am happy with the changes and reviews.

**Pull request merged**
