### PR TITLE
E3SM v1 LE (replace PR #10)

### PR DESCRIPTION
**Pull request by TonyB9000**
I copied "hist-aer r1-r5" to "hist-nat r1-r5".  Now branch_time_in_parent should grow correctly.

I used "hist-nat ..." for experiment_id, but for history I gave "hist-all-xGHG-xaer ...".  May need to do same for experiment_id.

We have 585 CMIP6 datasets to generate - this was the hold-up.  We can edit the datafiles later with Charlie's "ncatted" if we need to.

### CODE REVIEW

**Review by chengzhuzhang — CHANGES_REQUESTED** [review]
The comment session was deleted for all hist-nat json files. Please add them back. Also please check if the comment is included in the generated hist-nat files. Thanks!

**Comment by TonyB9000** [comment]
@chengzhuzhang It seems that none of the v2 metadata files have a comment section.  How can I "add them back"?
I think these came from a v1 "historical" metadata (?)

1pctCO2_r1i1p1f1.json:  "comment": "",
abrupt-4xCO2_r1i1p1f1.json:  "comment": "",
abrupt-4xCO2_r2i1p1f1.json:  "comment": "",
amip_r1i1p1f1.json:  "comment": "",
amip_r2i1p1f1.json:  "comment": "",
amip_r3i1p1f1.json:  "comment": "",
hist-aer_r1i1p1f1.json:  "comment": "",
hist-aer_r2i1p1f1.json:  "comment": "",
hist-aer_r3i1p1f1.json:  "comment": "",
hist-aer_r4i1p1f1.json:  "comment": "",
hist-aer_r5i1p1f1.json:  "comment": "",
hist-GHG_r1i1p1f1.json:  "comment": "",
hist-GHG_r2i1p1f1.json:  "comment": "",
hist-GHG_r3i1p1f1.json:  "comment": "",
hist-GHG_r4i1p1f1.json:  "comment": "",
hist-GHG_r5i1p1f1.json:  "comment": "",
hist-nat_r1i1p1f1.json:  "comment": "",
hist-nat_r2i1p1f1.json:  "comment": "",
hist-nat_r3i1p1f1.json:  "comment": "",
hist-nat_r4i1p1f1.json:  "comment": "",
hist-nat_r5i1p1f1.json:  "comment": "",
historical_r1i1p1f1.json:  "comment": "",
historical_r2i1p1f1.json:  "comment": "",
historical_r3i1p1f1.json:  "comment": "",
historical_r4i1p1f1.json:  "comment": "",
historical_r5i1p1f1.json:  "comment": "",
piClim-control_r1i1p1f1.json:  "comment": "",
piClim-histaer_r1i1p1f1.json:  "comment": "",
piClim-histaer_r2i1p1f1.json:  "comment": "",
piClim-histaer_r3i1p1f1.json:  "comment": "",
piClim-histall_r1i1p1f1.json:  "comment": "",
piClim-histall_r2i1p1f1.json:  "comment": "",
piClim-histall_r3i1p1f1.json:  "comment": "",
piControl_r1i1p1f1.json:  "comment": "",

The ONLY comment in the E3SM-1-0 metadata is in piControl.  All others are empty.

1pctCO2_r1i1p1f1.json:  "comment": "",
abrupt-4xCO2_r1i1p1f1.json:  "comment": "",
amip_allF_ens1.json:  "comment": "",
amip_allF_ens2.json:  "comment": "",
amip_allF_ens3.json:  "comment": "",
amip_r1i1p1f1.json:  "comment": "",
amip_r2i1p1f1.json:  "comment": "",
amip_r3i1p1f1.json:  "comment": "",
hist-GHG_r1i1p1f1.json:  "comment": "",
hist-GHG_r2i1p1f1.json:  "comment": "",
hist-GHG_r3i1p1f1.json:  "comment": "",
historical_r1i1p1f1.json:  "comment": "",
historical_r2i1p1f1.json:  "comment": "",
historical_r3i1p1f1.json:  "comment": "",
historical_r4i1p1f1.json:  "comment": "",
historical_r5i1p1f1.json:  "comment": "",
piControl_r1i1p1f1.json:  "comment": " piControl was configured to adhere as closely as possible with the CMIP6 DECK specifications (Eyring at al. 2016, GMD) with prescribed forcings appropriate for 1850 conditions. The simulation was run with time invariant forcings for a total of 500 years. To reduce spin-up time of the deep ocean, the simulation was initialized from a series of pre-existing control simulations performed with developmental versions of E3SM v1 as part of the final tuning phase (approximately 400 years). The final model tuning consisted of minor adjustments to cloud parameters with the objectives of achieving (1) near zero net top-of-atmosphere (TOA) radiation balance and (2) stable global mean surface air temperature.",
ssp585_r1i1p1f1.json:  "comment": "",
ssp585_r2i1p1f1.json:  "comment": "",
ssp585_r3i1p1f1.json:  "comment": "",
ssp585_r4i1p1f1.json:  "comment": "",
ssp585_r5i1p1f1.json:  "comment": "",

**Comment by chengzhuzhang** [comment]
Here shows how the comments are deleted: https://github.com/E3SM-Project/CMIP6-Metadata/pull/11/commits/5d93ccfd2bb23ff63250e0e0dadb3d10d3cc007e

**Comment by TonyB9000** [comment]
Very curious.  I  would not have intentionally made any edits to comments.  It suggests that I produced "my" version of these from copying over the other files (hist-aer, etc).

So, ONLY hist-nat should have this comment (obviously).  The others are OK empty?

**Comment by chengzhuzhang** [comment]
yes, ONLY hist-nat needs them. I thought the hist-nat.json files were accurate, not sure why you copied over and re-generated them. Perhaps you started with a branch that does not have hist-nat.json files..

**Comment by chengzhuzhang** [comment]
@TonyB9000 it looks like you are using this PR to also address adding v1_LE, could you also use the history column https://github.com/E3SM-Project/CMIP6-Metadata/pull/10#issuecomment-1353746155 to fill in the "history" attribute?

**Comment by TonyB9000** [comment]
Yes, that was likely the issue - bummer.

All have been updated.  I can use ncatted to update the metadata in all of the hist-nat CMIP6 files (530 sets), but as they were already published, they will need to be republished (else the checksums will no longer match.)

**Comment by TonyB9000** [comment]
All v1_LE metadata now have the proper history attribute.

**Review by chengzhuzhang — APPROVED** [review]

**Comment by chengzhuzhang** [comment]
Hey @TonyB9000 I renamed this PR and will merge. Thank you!

**Pull request merged**
