### PR TITLE
1 0 hist ghg ssp585 realization fix

### PR DESCRIPTION
**Pull request by chengzhuzhang**
A fix for realization change, which was missed from last PR.

### CODE REVIEW

**Review by TonyB9000 — APPROVED** [review]
"realization_index"?  Who would have known?  I was seeking "variant_label"...

**Comment by TonyB9000** [comment]
You do realize, this still leaves quite hidden the "code mechanism" wherein the created output directory (in warehouse) is generated.  At the very least, I cannot find it.

**Comment by chengzhuzhang** [comment]
@TonyB9000 the "code mechanism" for output directory structure and file names should be defined somewhere in cmor code base..https://github.com/PCMDI/cmor

**Comment by TonyB9000** [comment]
Thanks!  Given the DataSM code structure as driver (which ordinarily controls the flow of data processing), I would never have known to look there.  Personally, I think it is unwise to delegate that function in this manner.  At least, it is no-where explicit in the DataSM code that this delegation has taken place.

**Comment by chengzhuzhang** [comment]
yeah, DataSM calls e3sm_to_cmip, which calls cmor...

**Comment by TonyB9000** [comment]
Worse.  DataSM calls cwltool, which calls e3sm_to_cmip, which calls cmor...

**Pull request merged**
