### PR TITLE
add v2NARRM metadata definition

### LINKED ISSUE #13: Create Entries for E3SM-2-0-NARRM
New entries needed for E3SM-2-0-NARRM.

### PR DESCRIPTION
**Pull request by chengzhuzhang**
close #13

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@tangq hi, I just put together the metadata definition files needed to prepare NARRM data CMIP publication. It would be great to have you review the files. 

For the new NARRM metadate, I updated based on the v2.LR equivalent simulations. To facilitate reviewing, notable fields as shown below...

experiment_id | parent_experiment_id | source_type | activity_id | history | realization_index | branch_time_in_parent
-- | -- | -- | -- | -- | -- | --
piControl | piControl-spinup | AOGCM AER | CMIP | v2.NARRM.piControl | 1 | 0
1pctCO2 | piControl | AOGCM AER | CMIP | v2.NARRM.1pctCO2_0101 | 1 | 36500
abrupt-4xCO2 | piControl | AOGCM AER | CMIP | v2.NARRM.abrupt-4xCO2_0101 | 1 | 36500
amip | no parent | AGCM AER | CMIP | v2.NARRM.amip_0101 | 1 | 36500
amip | no parent | AGCM AER | CMIP | v2.NARRM.amip_0201 | 2 | 73000
amip | no parent | AGCM AER | CMIP | v2.NARRM.amip_0301 | 3 | 109500
historical | piControl | AOGCM AER | CMIP | v2.NARRM.historical_0101 | 1 | 36500
historical | piControl | AOGCM AER | CMIP | v2.NARRM.historical_0151 | 2 | 54750
historical | piControl | AOGCM AER | CMIP | v2.NARRM.historical_0201 | 3 | 73000
historical | piControl | AOGCM AER | CMIP | v2.NARRM.historical_0251 | 4 | 91250
historical | piControl | AOGCM AER | CMIP | v2.NARRM.historical_0301 | 5 | 109500

For reference, I used "Tang, Qi, Jean-Christophe Golaz, Luke P. Van Roekel, Mark A. Taylor, Wuyin Lin, Benjamin R. Hillman, Paul A. Ullrich et al. The Fully Coupled Regionally Refined Model of E3SM Version 2: Overview of the Atmosphere, Land, and River. GMD: https://doi.org/10.5194/gmd-2022-262; http://e3sm.org"

Please let me know if above is okay with you and any changes are needed. Thank you!

**Comment by tangq** [comment]
@chengzhuzhang , the information looks good to me based on a quick check. Can we wait a bit to merge this? Because the reference for the RRM overview is for the pre-print GMDD version. We are about to submit the revised version (waiting for co-author inputs) and should be able to have the final reference soon. It would be good to include the final reference in the meta data.

**Comment by chengzhuzhang** [comment]
Thank you for reviewing, @tangq. Yes, I can have this PR open until reference is finalized.

**Comment by chengzhuzhang** [comment]
@tangq hey Qi, just to check do you get the reference finalized? It seems like the doi is the same?

**Comment by tangq** [comment]
@chengzhuzhang , the manuscript is undergone typesetting right now and will be assigned the final DOI when that's done. The current DOI is only for the discussion version and should not be used here. I will updated the DOI when I have it.  Thanks for checking.

**Comment by chengzhuzhang** [comment]
Sounds good. Thank you!

**Comment by chengzhuzhang** [comment]
Hi @tangq , congrats on the paper publication. For data publication to CMIP. Tony has completed all the NARRM simulation for CMIP submission (except for Ocean and Sea-ice data from historical ensemble 2, due to gaps in data). The final doi seems to be ready. We will plan to replace current doi with https://doi.org/10.5194/gmd-16-3953-2023. and move forward with publishing.

**Comment by tangq** [comment]
Thank you, @chengzhuzhang , for following up on this. Yes, the final doi is 10.5194/gmd-16-3953-2023. Please update it and finalize the publishing process.

**Pull request merged**
